spring:
  application:
    name: legit
  profiles:
    active: prod
  flyway:
    placeholder-replacement: false

server:
  port: ${PORT:8080}

app:
  security:
    jwt:
      header: "Authorization"
      prefix: "Bearer "