ALTER TABLE users
ADD COLUMN IF NOT EXISTS avatar_url TEXT DEFAULT NULL;

ALTER TABLE law_firms
ADD COLUMN IF NOT EXISTS logo_url TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS cover_photo_url TEXT DEFAULT NULL;

ALTER TABLE client_profiles
ADD COLUMN IF NOT EXISTS company_logo_url TEXT DEFAULT NULL;
